apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2022-11-03T03:10:23Z"
  generation: 5
  labels:
    app: nginx-1
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"clean-jupiter-flash-repo-sha256-1"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"ALT_RPC_LIST"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"DEBUG"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"DEFAULT_RPC"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"SKIP_INTRO"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"SOLANA_WALLET_PRIVATE_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"TRADING_ENABLED"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"UI_COLOR"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"WRAP_UNWRAP_SOL"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2022-11-03T03:10:23Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2022-11-03T03:27:17Z"
  name: nginx-1
  namespace: default
  resourceVersion: "39518"
  uid: 969df958-0243-4e91-b46c-d8d982e1f2b8
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
      - env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: DEBUG
              name: nginx-1-config-k8vn
        - name: SKIP_INTRO
          valueFrom:
            configMapKeyRef:
              key: SKIP_INTRO
              name: nginx-1-config-k8vn
        - name: UI_COLOR
          valueFrom:
            configMapKeyRef:
              key: UI_COLOR
              name: nginx-1-config-k8vn
        - name: TRADING_ENABLED
          valueFrom:
            configMapKeyRef:
              key: TRADING_ENABLED
              name: nginx-1-config-k8vn
        - name: WRAP_UNWRAP_SOL
          valueFrom:
            configMapKeyRef:
              key: WRAP_UNWRAP_SOL
              name: nginx-1-config-k8vn
        - name: SOLANA_WALLET_PRIVATE_KEY
          valueFrom:
            configMapKeyRef:
              key: SOLANA_WALLET_PRIVATE_KEY
              name: nginx-1-config-k8vn
        - name: DEFAULT_RPC
          valueFrom:
            configMapKeyRef:
              key: DEFAULT_RPC
              name: nginx-1-config-k8vn
        - name: ALT_RPC_LIST
          valueFrom:
            configMapKeyRef:
              key: ALT_RPC_LIST
              name: nginx-1-config-k8vn
        - name: minPercProfit
          valueFrom:
            configMapKeyRef:
              key: minPercProfit
              name: nginx-1-config-k8vn
        image: gcr.io/extreme-hull-360811/clean-jupiter-flash-repo@sha256:41870f3072596ffd309f7b7c820ab36ecba690b832e997ab70f3da50c6ed30de
        imagePullPolicy: IfNotPresent
        name: clean-jupiter-flash-repo-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2022-11-03T03:28:18Z"
    lastUpdateTime: "2022-11-03T03:28:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-11-03T03:10:23Z"
    lastUpdateTime: "2022-11-03T03:28:19Z"
    message: ReplicaSet "nginx-1-5994f6864f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
